version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # synching the default.conf with nginx container ro for read only
  node-app:
    build: .
    #ports:
    #  - "3000:3000"
    environment:
      - PORT=3000 # from this line above config are common in both dev and prod environment
  # name of new service can be anything
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jasmeet
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db # stores the volume with name mongo-db
  redis:
    image: redis
volumes:
  mongo-db:
