version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      #specifies location of the docker file
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node server.js
